version: 2.1

orbs:
    slack: smaant/slack@0.0.3

jobs:
  build:
    docker:
        - image: smaant/web-screenshot:1.2

        - image: smaant/web-screenshot:1.2

    steps:
        - checkout

#        - run: 
#            name: Sleep
#            command: |
#                export HOUR=`date --utc +"%H"`
#                echo "hour:$HOUR"
#
#                # if current hour >= 7am PST && current hour <= 8am PST
#                if [ ${HOUR} -ge 14 ] && [ ${HOUR} -le 15 ]; then
#                    echo "MORNING"
#                    sleep $MORNING_SLEEP_TIME
#                else
#                    echo "DAY"
#                    sleep $DAY_SLEEP_TIME
#                fi

        - run:
            name: Get Prev
            command: |
                export PREV_BUILD_NUM=`curl "https://circleci.com/api/v1.1/project/github/smaant/visualtracker/tree/$CIRCLE_BRANCH?limit=1&filter=completed" -H "Circle-Token:$CIRCLECI_API_KEY" | jq '.[].build_num'`
                echo "Prev build: $PREV_BUILD_NUM"
                if [ ! -z $PREV_BUILD_NUM ]; then
                    export ARTIFACTS=`curl "https://circleci.com/api/v1.1/project/github/smaant/visualtracker/$PREV_BUILD_NUM/artifacts" -H "Circle-Token:$CIRCLECI_API_KEY" | jq -c -r '.[] | "\(.path), \(.url)"'`
                    echo "Artifacts: $ARTIFACTS"
                    mkdir prev
                    while IFS= read -r line; do
                        if [ ! -z "$line" ]; then
                            echo "Artifact: $line"
                            IFS=', ' read -r -a array \<<< "$line"
                            curl -L -o prev/${array[0]} "${array[1]}"
                        fi        
                    done \<<< "$ARTIFACTS"
                fi

        - run:
            name: Get Image
            command: |
                curl -o img.png `cat url.txt`

                if [ ! -f 'prev/img.png' ]; then
                    mkdir -p prev
                    echo "Copying img.png into prev/"
                    cp img.png prev/img.png
                fi

        # - run:
        #     name: Trigger next build 
        #     when: always
        #     command: |
        #         if ${CONTINUE:-false}; then
        #             curl -X POST "https://circleci.com/api/v2/project/github/smaant/visualtracker/pipeline" -H "Circle-Token:$CIRCLECI_API_KEY" -H "Content-Type:application/json" -d "{\"branch\": \"$CIRCLE_BRANCH\"}"
        #         fi

        - run: 
            name: Compare Images
            command: diff img.png prev/img.png

        - store_artifacts:
            path: img.png

        - slack/status:
            fail_only: true
            include_job_number_field: false
            include_project_field: false
            run: |
                export IMG=`curl "https://circleci.com/api/v1.1/project/github/smaant/visualtracker/$CIRCLE_BUILD_NUM/artifacts" -H "Circle-Token:$CIRCLECI_API_KEY" | jq -c -r '.[].url'`
                echo "Artificat img: $IMG"
            image_url: $IMG
            failure_message: https://www.roguefitness.com/rogue-color-echo-bumper-plate

workflows:
    version: 2
    main:
        jobs:
            - build:
                context: visualtracker
