version: 2.1
jobs:
  build:
    docker:
        - image: smaant/web-screenshot:1.1

        - image: smaant/web-screenshot:1.1

    steps:
        - checkout

        - restore_cache:
            key: v1-{{ .Branch }}

        - run:
            name: Get Image
            command: |
                ls
                curl -o img.png `cat url.txt`
                if [ -d 'prev' ]; then
                    # copy prev image for comparison
                    cp prev/img.png prev_img.png

                    # replacing prev image with the current on to be cached
                    cp img.png prev/img.png

                    # comparing current image and the copied previous one
                    exit `diff img.png prev_img.png`
                else
                    mkdir prev
                    cp img.png prev/img.png
                fi

        - store_artifacts:
            path: img.png

        - save_cache:
            key: v1-{{ .Branch }}
            paths:
                - ./prev

