version: 2.1
jobs:
  build:
    docker:
        - image: smaant/web-screenshot:1.1

        - image: smaant/web-screenshot:1.1

    steps:
        - checkout

        - restore_cache:
            key: v1-{{ .Branch }}

        - run:
            name: Get Image
            command: |
                ls
                export URL=`cat url.txt`
                curl -o img.png $URL
                if [ -d 'prev' ]; then
                    mkdir prev
                    cp img.png prev/img.png
                else
                    exit `diff img.png prev/img.png`
                fi

        - store_artifacts:
            path: img.png

        - save_cache:
            key: v1-{{ .Branch }}
            paths:
                - ./prev

