version: 2.1
jobs:
  build:
    docker:
        - image: smaant/web-screenshot:1.0

        - image: smaant/web-screenshot:1.0

    steps:
        - checkout

        - run:
            name: Get Image
            command: |
                export URL=`cat url.txt`
                curl -o img.png $URL

        - store_artifacts:
            path: img.png

